name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Echo boost
        run: "echo ${env:BOOST_ROOT_1_72_0}"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add Msbuild To PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
         vs-version: '16.5'

      - name: Restore Nuget Packages
        run: |
          cd msvc
          nuget restore
          cd ..

      - name: Setup Environment
        run: |
          echo "{BOOST_ROOT}={${env:BOOST_ROOT_1_72_0}}" >> $GITHUB_ENV
          echo "{BOOST_LIBRARYDIR}={${env:BOOST_ROOT_1_72_0}\\lib}" >> $GITHUB_ENV
          echo "${env:BOOST_ROOT}"
          echo "${env:BOOST_LIBRARYDIR}"
      
      - name: Run Build
        run: msbuild msvc/UKControllerPlugin.sln /property:Configuration=Release

      - name: Run Tests
        run: ".\\bin\\Release\\UKControllerPluginTest.exe"

      - name: Install Cpplint
        run: pip install cpplint

      - name: Run Lint
        run: cpplint --quiet --recursive src/ test/