name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Add Msbuild To PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
         vs-version: '16.5'

      - name: Restore Nuget Packages
        run: |
          cd msvc
          nuget restore
          cd ..

      - name: Setup Boost
        run: |
          echo "BOOST_ROOT=${env:BOOST_ROOT_1_72_0}\\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "BOOST_LIBRARYDIR=${env:BOOST_ROOT_1_72_0}\\lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      
      - name: Run Build
        run: msbuild msvc/UKControllerPlugin.sln /property:Configuration=Release

      - name: Run Tests
        run: ".\\bin\\Release\\UKControllerPluginTest.exe"

      - name: Install Cpplint
        run: pip install cpplint

      - name: Run Lint
        run: cpplint --quiet --recursive src/ test/