name: Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:       
      - name: Checkout Code
        uses: actions/checkout@v2

      # Environment things
      - name: Add Msbuild To PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
         vs-version: '16.5'

      - name: Setup Boost Environment
        run: |
          echo "BOOST_ROOT=${env:BOOST_ROOT_1_72_0}\\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "BOOST_LIBRARYDIR=${env:BOOST_ROOT_1_72_0}\\lib" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Cache OpenSSL
        id: cache-openssl
        uses: actions/cache@v2.1.3
        with:
          path: "C:\\Program Files\\OpenSSL-Win32"
          key: "ukcp-openssl"

      - name: Install OpenSSL
        if: steps.cache-cache-openssl.outputs.cache-hit != 'true'
        run: choco install openssl --limitoutput --x86

      - name: Echo OpenSSL
        run: dir "C:\\Program Files\\OpenSSL-Win32"

      - name: Setup OpenSSL Environment
        run: |
          echo "OPENSSL_ROOT=C:\\Program Files\\OpenSSL-Win32\\include" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "OPENSSL_LIBRARYDIR=C:\\Program Files\\OpenSSL-Win32\\lib\\VC\\static" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Restore Nuget Packages
        run: |
          cd msvc
          nuget restore
          cd ..
      
      # Run the build and tests
      - name: Run Build
        run: msbuild msvc/UKControllerPlugin.sln /property:Configuration=Release -m

      - name: Run Tests
        run: ".\\bin\\Release\\UKControllerPluginTest.exe"

      # Run the linter
      - name: Install Cpplint
        run: pip install cpplint

      - name: Run Lint
        run: cpplint --quiet --recursive src/ test/